version: '3.8'

networks:
  unionus:
    name: unionus
    driver: bridge
    external: true

services:
  host:
    container_name: ${PROJECT_NAME}-host
    build:
      context: .
      dockerfile: Dockerfile_host
    networks:
      - unionus
    volumes:
      - ./fpm/:/var/www/html
    ports:
      - "80:80"
      - "443:443"
  fpm:
    container_name: ${PROJECT_NAME}-fpm
    build:
      context: .
      dockerfile: Dockerfile_fpm
    networks:
      - unionus
    volumes:
      - ./fpm/:/var/www/html
    ports:
      - "9000:9000"
  database:
    container_name: ${PROJECT_NAME}-database
    build:
      context: .
      dockerfile: Dockerfile_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - unionus
    command: --wait_timeout=3600
    ports:
      - "3306:3306"