<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerODx47uF\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerODx47uF/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerODx47uF.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerODx47uF\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerODx47uF\App_KernelProdContainer([
    'container.build_hash' => 'ODx47uF',
    'container.build_id' => '194bce2c',
    'container.build_time' => 1710180114,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerODx47uF');
