<?php

namespace ContainerH5WxGga;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fmp8pCtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fmp8pCt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fmp8pCt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'mailer' => '?',
            'registry' => '?',
        ]);
    }
}
