# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    email:
        enabled: true                  # If email authentication should be enabled, default false
        sender_email: noreply@yourdwell.ru   # Sender email address
        sender_name: Secret Santa          # Sender name
        digits: 4                      # Number of digits in authentication code
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
